import Navigation from '@/components/Navigation';
import './globals.css'

export const metadata = {
  title: 'My First Nextjs 13',
  description: 'Generated by create next app',

}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/5/flatly/bootstrap.min.css" />
      </head>
      <body>
        <Navigation />
        <div className="container p-4">
          {children}
        </div>



      </body>
    </html>
  )
}
